In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
car_df = pd.read_csv('/content/car_age_price.csv')

In [57]:
car_df.head()

   Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [58]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    112 non-null    int64
 1   Price   112 non-null    int64
dtypes: int64(2)
memory usage: 1.9 KB

In [59]:
car_df.describe()

              Year          Price
count   112.000000     112.000000
mean   2016.669643  483866.044643
std       1.629616   91217.450533
min    2013.000000  300000.000000
25%    2015.000000  423750.000000
50%    2017.000000  500000.000000
75%    2017.000000  550000.000000
max    2020.000000  755000.000000

In [60]:
car_df.isnull().sum()

Year     0
Price    0
dtype: int64

In [61]:
car_df.shape

(112, 2)

In [62]:
car_df.index

RangeIndex(start=0, stop=112, step=1)

In [63]:
car_df.duplicated().sum()

np.int64(54)

In [64]:
X =car_df[['Year']]
y =car_df[['Price']]

In [65]:
car_df.corr()

           Year     Price
Year   1.000000  0.776302
Price  0.776302  1.000000

In [77]:
lr = LinearRegression()

In [82]:
lr.fit(x_train, y_train)

LinearRegression()

In [83]:
y_pred = lr.predict(x_test)

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    X,y,test_size = 0.2, random_state = 42
)

In [26]:
y_pred

array([[600775.91252081],
       [505558.77690466],
       [553167.34471273],
       [553167.34471273],
       [553167.34471273],
       [410341.6412885 ],
       [505558.77690466],
       [553167.34471273],
       [600775.91252081],
       [600775.91252081],
       [315124.50567235],
       [505558.77690466],
       [410341.6412885 ],
       [648384.48032889],
       [553167.34471273],
       [600775.91252081],
       [315124.50567235],
       [410341.6412885 ],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466]])

In [27]:
y_test

      Price
40   525000
65   495000
4    465000
47   450000
42   550000
69   300000
26   550000
11   500000
10   500000
44   550000
73   320000
55   550000
68   465000
97   640000
0    465000
18   500000
53   345000
80   390000
103  375000
91   520000
36   550000
12   500000
31   550000

In [28]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 4326906256.829671
R-squared: 0.36759313425902185

In [69]:
price_pred = lr.predict([[2022]])
price_pred

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[743601.61594504]])

In [70]:
from sklearn.linear_model import Lasso

In [71]:
model = Lasso(alpha=0.1)
model.fit(x_train, y_train)

Lasso(alpha=0.1)

In [72]:
price_pred = model.predict([[2022]])
price_pred

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(

array([743601.39177768])

In [73]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("R-squared:", r2_score(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

R-squared: 0.36759313425902185
Mean Absolute Error: 53534.77957001264
Mean Squared Error: 4326906256.829671

In [74]:
from sklearn.metrics import mean_squared_error, r2_score

y_pred_lasso = model.predict(x_test)

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("Lasso Mean Squared Error:", mse_lasso)
print("Lasso R-squared:", r2_lasso)

Lasso Mean Squared Error: 4326901608.19506
Lasso R-squared: 0.36759381368868127

In [75]:
print("Linear Regression R2:", r2)
print("Lasso Regression R2:", r2_lasso)

Linear Regression R2: 0.36759313425902185
Lasso Regression R2: 0.36759381368868127

In [76]:
#: Lasso Regression performs slightly better than Linear Regression based on R² score